/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Classes.Consulta;
import Classes.Datas;
import Classes.MysqlConec.ConsultaOpc;
import Classes.MysqlConec.MedicoOpc;
import Classes.MysqlConec.pacienteOpc;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author diógenes
 */
public final class AgendarConsulta extends javax.swing.JFrame {
    CadastroMedico medicoclasse =new CadastroMedico();
     MedicoOpc medico = new MedicoOpc();
     pacienteOpc paciente = new pacienteOpc();
     int num;
    /*
     * Creates new form MarcarConsulta
     */
    public AgendarConsulta() {
        initComponents();
        medicoclasse.preencherEspecialidade(jespecialidade);
        preencherMedico( jmedico);
        preencherPaciente( jpaciente);
    }
    public void preencherMedico( javax.swing.JComboBox<String> combo){
          
             List<String> nomes = medico.listarEsp();
        DefaultComboBoxModel<String> lista=new DefaultComboBoxModel<> (); 
        for(String itens:nomes ){
            lista.addElement(itens);
        }
         combo.setModel(lista);
         
    }
 
    public void preencherPaciente( javax.swing.JComboBox<String> combo){
           pacienteOpc paciente = new pacienteOpc();
             List<String> nomes = paciente.listarPaciente();
        DefaultComboBoxModel<String> lista=new DefaultComboBoxModel<> (); 
        for(String itens:nomes ){
            lista.addElement(itens);
        }
         combo.setModel(lista);
    
         
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jpaciente = new javax.swing.JComboBox<>();
        voltar = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jmedico = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jespecialidade = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jhora = new javax.swing.JComboBox<>();
        jmin = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jdia = new javax.swing.JComboBox<>();
        jmes = new javax.swing.JComboBox<>();
        jano = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Confirmar = new javax.swing.JToggleButton();
        Cadastrar = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AGENDAR CONSULTA");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 100, 148));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Paciente:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 233, -1, -1));

        jpaciente.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        jpaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " ", " ", " ", " ", " ", " " }));
        jpaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpacienteActionPerformed(evt);
            }
        });
        jPanel1.add(jpaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 230, 220, -1));

        voltar.setBackground(new java.awt.Color(255, 204, 51));
        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/previous.png"))); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        jPanel1.add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Especialidade: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 80, -1));

        jmedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " ", " ", " ", " ", " ", " " }));
        jmedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmedicoActionPerformed(evt);
            }
        });
        jPanel1.add(jmedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 151, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Medico: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 55, -1));

        jespecialidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " ", " ", " ", " " }));
        jespecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jespecialidadeActionPerformed(evt);
            }
        });
        jPanel1.add(jespecialidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 151, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data da Consulta: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 358, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 407, -1, -1));

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 407, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 100, 148));

        jhora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));

        jmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55", " " }));
        jmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jhora, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmin, 0, 50, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jhora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 366, -1, -1));

        jPanel6.setBackground(new java.awt.Color(0, 100, 148));

        jdia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));

        jmes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmesActionPerformed(evt);
            }
        });

        jano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2025" }));
        jano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                janoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jdia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jano, 0, 66, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 374, 180, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Horário: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 55, -1));

        Confirmar.setBackground(new java.awt.Color(255, 204, 51));
        Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mark.png"))); // NOI18N
        Confirmar.setText("Confirmar");
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(Confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, -1, -1));

        Cadastrar.setBackground(new java.awt.Color(255, 204, 51));
        Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        Cadastrar.setText("Novo");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(Cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 232, -1, 20));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo-giraa-1 (1)c_1.png"))); // NOI18N
        jLabel1.setText("      CLINICA GIRASSOL");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 642, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        TelaAdm telaA = new TelaAdm (); 
         this.dispose();
        telaA.setVisible(true);
        
    }//GEN-LAST:event_voltarActionPerformed
     private void pegarIdMedico() {
        String medicoSelecionado = jmedico.getSelectedItem().toString();
                    medico.setN_ordem(medico.idMedico(medicoSelecionado));
                    
        System.out.println(medico.getN_ordem()+" oLHA AQUI ");
    
    }
    private void jmedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmedicoActionPerformed
        // TODO add your handling code here:
        pegarIdMedico();
        Datas data=new Datas ();
        data.PegarData("20/12/2000");
        
        System.out.println(data.getMes()+ "  " + data.MostrarData());
        
    }//GEN-LAST:event_jmedicoActionPerformed

    private void jespecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jespecialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jespecialidadeActionPerformed

    private void jminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jminActionPerformed

    private void jmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmesActionPerformed

    private void janoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_janoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_janoActionPerformed

    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
        // TODO add your handling code here:
        Datas dt = new Datas();
        dt.setAno(Integer.valueOf(jano.getSelectedItem().toString()));
        dt.setDia(Integer.valueOf(jdia.getSelectedItem().toString()));
        dt.setDia(Integer.valueOf(jdia.getSelectedItem().toString()));
        
        
          Consulta con = new Consulta();
        con.setEstado("Pendente");
        con.setData(dt);
        con.setmedico(medico.getN_ordem());
        con.setnumdocIdent(paciente.getNumDocIdent());
        con.setEspecialidd(jespecialidade.getSelectedItem().toString());
        con.setHora((jhora.getSelectedItem().toString()));
        con.setMin((jmin.getSelectedItem().toString()));
        
        
        ConsultaOpc cs = new ConsultaOpc();
        try {
            cs.AgendarConsulta(con);
        } catch (Exception ex) {
            Logger.getLogger(AgendarConsulta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_ConfirmarActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        // TODO add your handling code here:
        CadastroPaciente tela1=new CadastroPaciente();
        this.dispose();
        tela1.setVisible(true);
        
    }//GEN-LAST:event_CadastrarActionPerformed
         private void pegarIdPaciente() {
        String medicoSelecionado = jpaciente.getSelectedItem().toString();
                    paciente.setNumDocIdent(paciente.idPaciente(medicoSelecionado));
                   System.out.println(paciente.getNumDocIdent()+"  "+ medicoSelecionado);}
    private void jpacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpacienteActionPerformed
        // TODO add your handling code here:
        pegarIdPaciente();
    }//GEN-LAST:event_jpacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendarConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Cadastrar;
    private javax.swing.JToggleButton Confirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JComboBox<String> jano;
    private javax.swing.JComboBox<String> jdia;
    private javax.swing.JComboBox<String> jespecialidade;
    private javax.swing.JComboBox<String> jhora;
    private javax.swing.JComboBox<String> jmedico;
    private javax.swing.JComboBox<String> jmes;
    private javax.swing.JComboBox<String> jmin;
    private javax.swing.JComboBox<String> jpaciente;
    private javax.swing.JToggleButton voltar;
    // End of variables declaration//GEN-END:variables

   
}
