/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Classes.MysqlConec.UserOpc;
import javax.swing.JOptionPane;

/**
 *
 * @author diógenes
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jusuario = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        Entrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Bell MT", 1, 10)); // NOI18N
        jLabel11.setText("Rua comandante Gika Nª 225, Bairro Alvalade");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Seja Bem-Vindo");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 190, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/usuario-do-circulo.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 150, 130));

        jLabel9.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Usuario");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 70, -1));

        jLabel10.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("PassWord:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 70, -1));

        jusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jusuarioActionPerformed(evt);
            }
        });
        jPanel2.add(jusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 150, -1));

        jPassword.setText("jPasswordField1");
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 150, -1));

        Entrar.setBackground(new java.awt.Color(255, 204, 51));
        Entrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Entrar.setForeground(new java.awt.Color(255, 255, 255));
        Entrar.setText("Entrar");
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });
        jPanel2.add(Entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo-giraa-1 (1)c_1.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 300, 140));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ENFERM~1.JPG"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 300, 370));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jusuarioActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
        // TODO add your handling code here:
        UserOpc usOpc = new UserOpc();
         char [] letrasDaPasse= jPassword.getPassword();
        String password = new String(letrasDaPasse);
        
        /*System.out.println(usOp.cargo(1002));
        System.out.println(usOp.palavraPass(1002));
        String sec ="z";*/
        if (!jusuario.getText().matches("^[0-9]+$" ) || !password.matches("^[0-9]+$" ) ){
                    JOptionPane.showMessageDialog(null, "Verifique a Palavra"); 
        } else {
        
        String opc;
        opc = usOpc.cargo(Integer.parseInt(jusuario.getText()));
       
        if(opc != null){
                   
       
        switch(opc){
            case" Medico":
                if (usOpc.palavraPass(Integer.parseInt(jusuario.getText()))==Integer.parseInt(password)){
              TelaMedico md = new TelaMedico();
              this.dispose();
              md.setVisible(true);
            } else {
                     JOptionPane.showMessageDialog(null, "Palavra pass Incorreta");                
                   }
                break;
            case "Recepcionista":
                 if (usOpc.palavraPass(Integer.parseInt(jusuario.getText()))== Integer.parseInt(password)){
              TelaAtendente md = new TelaAtendente();
              this.dispose();
              md.setVisible(true);
            
            } else {
                     JOptionPane.showMessageDialog(null, "Palavra pass Incorreta");
        
        
                    }
                break;
                
        case "Administrador":
              if (usOpc.palavraPass(Integer.valueOf(jusuario.getText()))== Integer.parseInt(password)){
              TelaAdm md = new TelaAdm();
              this.dispose();
              md.setVisible(true);  
            } else {
                     JOptionPane.showMessageDialog(null, "Palavra pass Incorreta");
             } 
              break;
                
        default : 
            JOptionPane.showMessageDialog(null, "Usuario Desconhecido"); 
        
        
        }
        } else{
        
                    JOptionPane.showMessageDialog(null, "Verifique a pass ou o usuário"); 

        }
        }
     
    }//GEN-LAST:event_EntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jusuario;
    // End of variables declaration//GEN-END:variables
}
