/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author diógenes
 */
public class TelaAtendente extends javax.swing.JFrame {

    /**
     * Creates new form TelaAtendente
     */
    public TelaAtendente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Botao_Agenda_Consulta = new javax.swing.JToggleButton();
        Listar_Consulta = new javax.swing.JToggleButton();
        ListarCliente = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 100, 148));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Botao_Agenda_Consulta.setBackground(new java.awt.Color(255, 204, 51));
        Botao_Agenda_Consulta.setText("Agendar Consulta");
        Botao_Agenda_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_Agenda_ConsultaActionPerformed(evt);
            }
        });
        jPanel1.add(Botao_Agenda_Consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 147, -1));

        Listar_Consulta.setBackground(new java.awt.Color(255, 204, 51));
        Listar_Consulta.setText("listar Consulta");
        Listar_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listar_ConsultaActionPerformed(evt);
            }
        });
        jPanel1.add(Listar_Consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 147, -1));

        ListarCliente.setBackground(new java.awt.Color(255, 204, 51));
        ListarCliente.setText("Listar Cliente");
        ListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(ListarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 147, -1));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 157, 156));

        jToggleButton1.setBackground(new java.awt.Color(255, 204, 51));
        jToggleButton1.setText("Cadastrar Paciente");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 147, -1));

        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CLÍNICA GIRASSOL");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 356, 32));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ENFERM~1.JPG"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, -20, 400, 450));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 157, 156));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Botao_Agenda_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_Agenda_ConsultaActionPerformed
        AgendarConsulta agendar=new AgendarConsulta();
        agendar.setVisible(true);
        dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_Botao_Agenda_ConsultaActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
          CadastroPaciente tela1=new CadastroPaciente();
        tela1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void Listar_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listar_ConsultaActionPerformed
        // TODO add your handling code here:
        ListraConsulta lista = new ListraConsulta(); 
        lista.setVisible(true);
        dispose();
    }//GEN-LAST:event_Listar_ConsultaActionPerformed

    private void ListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarClienteActionPerformed
        // TODO add your handling code here:
        ListraCliente tela = null;
        try {
            tela = new ListraCliente();
        } catch (Exception ex) {
            Logger.getLogger(TelaAtendente.class.getName()).log(Level.SEVERE, null, ex);
        }
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_ListarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtendente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Botao_Agenda_Consulta;
    private javax.swing.JToggleButton ListarCliente;
    private javax.swing.JToggleButton Listar_Consulta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
